### ISSUE TITLE
How to check whether a device is capable of performing passwordless auth?

### ISSUE THREAD

**Issue by msschl** [dbfr3qs/PasswordlessAuthExample#1]
Is there a way to check whether a device is capable of performing passwordless auth before displaying the passwordless login button to the user?

**Comment by msschl** [comment]
Preferably a server-side check.

**Comment by dbfr3qs** [comment]
Hey @msschl, to my knowledge there is no way to do this server side. 

What you can do is check for WebAuthN support in the browser by doing something like:

```
if (PublicKeyCredential) {
   // display login button
}
```

... but this only checks if the browser supports the WebAuthN Api.

You can check for [the presence of a platform authenticator](https://developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredential/isUserVerifyingPlatformAuthenticatorAvailable) using a built in static method on the PublicKeyCredential class.

However, this does not support the use case of a roaming authenticator, such as a Yubikey. I have just tested this to make sure and this is the case. My [reading on the discussion on this](https://github.com/w3c/webauthn/issues/764#issuecomment-360742628) is that the spec is designed to support allowing users to plug in roaming authenticators during a registration or sign in flow, which makes sense.

Does that help answer your question?

**Comment by msschl** [comment]
Yes, thanks a lot 👍🏽
